### PR TITLE
Add log status at the bottom

### PR DESCRIPTION
**Pull request by ykazakov**
The changes add a log icon at the bottom of Protege window.
This icon can be used to monitor problems (warnings and errors) and quickly open the log.
Previously this has been handled only for errors (an error icon showed at the top) but the user was uninformed about the warnings (unless a log window is already opened). However, warnings are also important. E.g., a reasoner (like ELK) warns when the result is incomplete (see, e.g., #710), which could stay unnoticed.

### CODE REVIEW

**Comment by ykazakov** [comment]
I now have changed the implementation of the log window to use JTextPane instead of JList. Was there any deep reason to display the log in a list?

**Comment by ykazakov** [comment]
@matthewhorridge would you consider merging this pull request before the new release of Protege? It is essential for the new version of ELK.

**Comment by matthewhorridge** [comment]
@ykazakov sorry for not looking at this sooner.  Will take a look asap.  I might target this for beta-4 if that's okay.

**Comment by ykazakov** [comment]
beta-4 is ok, just wanted to be sure it is a part of the next Protege (non-beta) release

**Comment by matthewhorridge** [comment]
Excellent job with this @ykazakov.  Big improvement.  The only thing that bothers me is the removal of the View log menu item.

**Comment by matthewhorridge** [comment]
Merged in.  I've added the menu item back so that it's accessible from the menu.

**Comment by ykazakov** [comment]
Thanks for merging! I don't mind putting the menu back. It is probably a good idea as novice users might not notice the log icon.
Note that I also removed the menu for the timestamp as it is now available in the log window itself. I hope that is fine.

**Comment by matthewhorridge** [comment]
I've put the menu back in.  I think the timestamp button is better where it is.  Overall, this is a great improvement... very nice UI work!

**Comment by ykazakov** [comment]
I see. Thanks. Just downloaded the new version. Checking... The tooltip for the menu Window > Show Log... is the same as for Timestamp log / console. Probably copy & paste error.

**Comment by ykazakov** [comment]
Other than that looks good. Thanks again for merging!

**Pull request merged**
