### PR TITLE
Add DOI and WikipediaVersioned Extractor

### PR DESCRIPTION
**Pull request by shawntanzk**
Adding DOI and WikipediaVersioned (two things used quite often in a few of the obo foundry ontologies) 
Followed patterns from searching repo - probably needs a proper looking over to make sure I didn't do anything stupid. 
Tagging @hkir-dev & @matentzn 
Related to https://github.com/obophenotype/uberon/issues/1874

### CODE REVIEW

**Comment by shawntanzk** [comment]
@matentzn guess it lol - I can try building it, but currently don't have eclipse installed, and not sure even if I did I really know how to handle stuff. Was mostly doing this cause I had some free time and thought I'd try to take some workload off @hkir-dev (was hoping there was already mapping, but after search realised it was this way, so while I was at it, thought I'd do these changes following pattern, hence really needing proper looking over). 

> Or better yet, add support for an external prefix map?

100% would be keen for this, but it might be beyond my skillset

**Comment by hkir-dev** [comment]
Good progress @shawntanzk . Seems we need to fix the doi regex (though seems it is a little difficult to have a perfectly working one). We can work and test together.

@matentzn providing an external map might be the ultimate solution, but it will require a lot of changes (config menu updates, config file validation and processing etc.) It would be good to go iteratively and have a first version with the current design.

**Comment by matentzn** [comment]
Sound good @hkir-dev, can you perhaps add then OMIM, OMIMPS, DOI, ORCID, Orphanet? This would make some of our powerusers very happy!

**Comment by shawntanzk** [comment]
OMIM: https://omim.org/entry/
OMIMPS: https://www.omim.org/phenotypicSeries/
ORCID: https://orcid.org/
Orphanet: https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=

**Comment by hkir-dev** [comment]
Unit and manual tests completed, new extractors are working as expected.

**Comment by hkir-dev** [comment]
But observed a malfunction in the already existing OboFoundryLinkExtractor. 
`UBERON:0007329` is redirected to `identifiers.org/UBERON:0007329` instead of `purl.obolibrary.org/obo/UBERON_0007329`

I suspect about the order of IdentifiersDotOrgLinkExtractor and OboFoundryLinkExtractor but seems this order changed intentionally: https://github.com/protegeproject/protege/commit/dd514dea8b405e251018dad74d350407cabdc037

Independent from the current PR, this issue requires further analysis and a separate bug report.

**Comment by shawntanzk** [comment]
Thanks @hkir-dev, see you cleaned up some of my silly mistakes too heh, thanks heaps!

**Review by matentzn — APPROVED** [review]
Excellent @hkir-dev! Looks great!

**Comment by matthewhorridge** [comment]
This is a great contribution!  Thanks very much @shawntanzk.  We really appreciate it!

**Pull request merged**
