### PR TITLE
fix issue #279

### PR DESCRIPTION
**Pull request by jgrzebyta**
I have added throw to `createSearchRequest` Method (line 79):

```
private SearchRequest createSearchRequest() throws PatternSyntaxException {
...
}
```

... which is caught later inside method `doSearch()` (line 126):

```
try {
            searchRequest = createSearchRequest();
     } catch (PatternSyntaxException ex) {
            log.debug("entered pattern: '{}'", ex.getPattern());
            return;
      }
```

### CODE REVIEW

**Comment by matthewhorridge** [comment]
Thanks for the contribution.  I've already fixed this in the version-4 branch (which will be merged soon)

**Comment by jgrzebyta** [comment]
I have added 2 new changes: 
- removed file `protege-5.0.0-beta-18-SNAPSHOT-platform-independent.zip` from *protege-desktop*
- added possible solution for #271 : ontology name is displayed as italic:

onto-name

**Comment by jgrzebyta** [comment]
I found the solutions within version-4. Is that version ready to work on?

**Comment by matthewhorridge** [comment]
version-4 is in a bit of churn at the moment, but I expect to merge it into the master branch this week.

**Pull request closed without merging**
