### PR TITLE
Use dashes ('-') instead of underscores ('_') when generating random ids as UUIDs

### PR DESCRIPTION
**Pull request by tdstein**
The typical practice for random id generation is to use UUIDs in an 8-4-4-4-12 pattern with dashes.

### CODE REVIEW

**Comment by tdstein** [comment]
FYI - The build failure is the same as on the master branch.

**Comment by matthewhorridge** [comment]
Thanks for the PR.  Will look at it asap.  (We are working on the errors - due to a changed API at identifiers.org)

**Comment by tdstein** [comment]
@matthewhorridge - builds are passing now

**Comment by tdstein** [comment]
Hey @matthewhorridge, following up on this since it has been a while.

**Comment by matthewhorridge** [comment]
@tdstein thanks for the polite nudge :) Between other deadlines and vacations I've not had a chance to look at this properly.  However, on the surface, things look okay (and I prefer dashes).  I do have one concern however – existing ontology projects that currently use the UUID generation strategy may want to keep underscores for the purposes of uniformity.  Do you think you would be able to provide this as an option or would it be too much for you to do?

**Comment by tdstein** [comment]
No worries.

I agree. That crossed my mind as well. I was unsure of how breaking changes were handled in this project. 

I'll give it a shot. Do you have a preference for what the default is if I am able to figure it out?

**Comment by matthewhorridge** [comment]
Although my personal preference is for dashes, we'll probably have to go with underscores for backwards compatibility.

**Comment by tdstein** [comment]
@matthewhorridge - the most recent changes add a third option for UUIDs that acts exactly the same as the '_' version.

Screen Shot 2019-07-09 at 1 34 02 PM

**Comment by tdstein** [comment]
Closing this PR since it's stale.

**Pull request closed without merging**
