### PR TITLE
Ontology save popup should be disappearing properly

### PR DESCRIPTION
**Pull request by lks128**
This pull request should be fixing issue #574.

### CODE REVIEW

**Comment by matthewhorridge** [comment]
I'm surprised this would fix the reported problem.  In any case, the dialog should be disposed like this, so we'll go ahead with the merge.  Thanks for the contribution.

**Comment by ykazakov** [comment]
Surprisingly this patch indeed fixes  #574.
I think the problem was cased by [this open idk bug](https://bugs.openjdk.java.net/browse/JDK-5109571). Calling JDialog.dispose() instead (or in addition to) JDialog.setVisible(false) seems to avoid the stuck window.
I made a patch with a few further improvements.

**Comment by lks128** [comment]
Nice to hear it fixes the bug! Interesting that if we don't do
setVisible(false) before calling dispose(), the application will work on
Linux, but will get stuck on macOS. So the code needs both setVisible and
dispose. Don't know why this happens

19 янв. 2017 г. 11:53 пользователь "Yevgeny Kazakov" <
notifications@github.com> написал:

**Comment by ykazakov** [comment]
Hm... it does not get stuck for me.
Can you try running it from my code:

https://github.com/ykazakov/protege

I have submitted a pull request, bit it was was not merged yet.
There were a few other issues which could cause the stuck window that I
fixed.
E.g., in OntologySaver it was possible that dlg.setVisible(true) is called
after dlg.setVisible(false).

- Yevgeny

**Pull request merged**
