### PR TITLE
Fixed #186 and new IDE integration - please test in Eclipse!

### LINKED ISSUE #186: org.protege.editor.core.prefs.Preferences: clear() does not remove preferences of type list and array
Test on Protege-5.0.0-beta-17:

Protege provides a way to (permanently) store various values (preferences) using PreferencesManager and Preferences from the package org.protege.editor.core.prefs. Among the types of the values that can be stored are integers, booleans, floats, strings, but also it is possible to store lists of strings and arrays of bytes. Unfortunately, it does not seem to be possible to clear the list and array values using the Preferences.clear() method. The following test reproduces the problem: 

package org.protege.editor.core.prefs;

import static org.junit.Assert.assertTrue;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.junit.Test;

public class PreferencesTest {

	@Test
	public void testClearStringList() {
		PreferencesManager prefMan = PreferencesManager.getInstance();
		Preferences prefs = prefMan.getPreferencesForSet(
				"someRandomSetId#1973948103", "somePrefsId");
		prefs.clear(); // just in case there are values from the previous run
		String stringListKey = "someKey";
		List<String> defaultList = Arrays.asList("A", "B");
		List<String> list = prefs.getStringList(stringListKey, defaultList);
		assertTrue(list.equals(defaultList));

		List<String> newList = Arrays.asList("One", "Two", "Tree");
		prefs.putStringList(stringListKey, newList);

		list = prefs.getStringList(stringListKey,
				Collections.<String> emptyList());
		assertTrue(list.equals(newList));

		prefs.clear();
		list = prefs.getStringList(stringListKey, defaultList);
		assertTrue(list.equals(defaultList)); // <= TEST FAILS HERE
	}
}

The problem is the implementation of the method clear() of JavaBackedPreferencesImpl, which just calls clear() of java.util.prefs.Preferences and according to the documentation it "Removes all of the preferences (key-value associations) in this preference node. This call has no effect on any descendants of this node." But for lists and arrays the consequent values are stored in the descendant nodes.

### PR DESCRIPTION
**Pull request by ykazakov**
Here is a quick fix for the issue #186 I reported previously. I introduced tests to org.protege.editor.core.application, I hope you don't mid (more tests for org.protege.editor.core.prefs would actually be nice).

I also made some reorganisation for maven-bundle-plugin in pom files, in particularly for the ide maven profile to generate the files for Eclipse. 

The purpose of the new profile is to replace the (outdated and incomplete) method [here](http://protegewiki.stanford.edu/wiki/CompileProtege5InEclipseWithMaven).

The new ide profile is based on the recommended settings of [maven-bundle-plugin for Eclipse integration](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html) (see Eclipse/PDE integration)

The new profile is mainly used to copy settings.xml and the jars that should be embedded in plugins so that Eclipse PDE finds them. The method is more "native" than the method described on the [this wiki](https://github.com/protegeproject/protege/wiki/Setup-in-Eclipse) by @tudorache.

Essentially, one does not need to compile project using maven before running the project in Eclipse; instead of the maven compiler, the Eclipse (incremental) compiler is used

To run Protege in eclipse (with PDE integration) do the following:

### 0. prerequisites

Ensure that Eclipse PDE (Plug-in Development Environment) is installed in eclipse (e.g., from the Eclipse Marketplace)

### 1. checkout protege from github

    git clone https://github.com/ykazakov/protege.git protege

### 2. compile protege with the profile ide activated:

       mvn clean install -Pide

### 3. import the projects from eclipse: 

       File > Import > Maven > Existing Maven Projects 

select the parent pom.xml file in the protege git directory

### 4. import the third-party Protege bundles from the protege version compiled by maven:

    File > Import >  Plug-in Development > Plug-ins and Fragments >

(if you do not see "Plug-in Development" under `File > Import` then most likely Eclipse PDE is not installed)

select the following directory in the location where protege was cloned:

`protege/protege-desktop/target/protege-${version}-platform-independent/Protege-${version}/bundles`

under "Plug-ins and Fragments to Import" tick the first option:

    o "Select from all plug-ins and fragments found at the specified location"

under "Import As" tick the first option

    o "Binary projects" 

Press "Next >"

move all Plug-ins from the left to the right window *except* for those matching

    org.eclipse.equinox.*
    org.protege.*

(those will be used from the Eclipse workspace and Eclipse installation)

Press "Finish"

There might be errors (exclamation marks on the new projects in Eclipse) due to cyclic dependencies involving bundle `slf4j.api`, those can be changed to warnings in `Preferences > Java > Compiler > Building > Build path problems > Circular dependencies`)

### 5. Convert the following protege projects in the Eclipse workspace to bundles:
 
`
     protege-common, 
     protege-editor-core,
     protege-editor-owl
`
 
For each of these projects do:

* right click on the project: `Configure > Convert to Plug-in Projects...`
* (optional, if already converted and needs to be updated after maven recompilation) 
   right click on the project: `Plug-in Tools > Update Classpath...` (select all above projects) `> Finish`

### 6. Restore the maven dependencies (which are unfortunately deleted by updating Plug-in classpath):

 right click on `protege-parent`: `Maven > Update Project... > OK`

After Step 6 there should be no errors in eclipse workspace (no red marks)

### 7. Create Protege run/debug configuration (can be done largely as per [old instructions](http://protegewiki.stanford.edu/wiki/CompileProtege5InEclipseWithMaven)):

`Run > Run Configurations... > OSGi Framework > (right click) > New`

Bundles tab: deselect *all* projects, select *only* projects matching "org.protege.*" from Workspace, click "Add Required Bundles" on the right

change the "Start Level" of org.protege.editor.core.application from "default" to "1"

It is useful to verify missing dependencies by pressing "Validate Bundles"; 
(in my case I have only one problem with "org.eclipse.m2e.core" that requires com.google.guava version [14.0.1,16.0.0) which is strangely not found in eclipse bundles, but Protege nevertheless works)

Arguments tab: remove all arguments and replace them with:
"Program arguments:" 

    -consoleLog -console -nosplash

"VM arguments:" 

    -Xms250M -Xmx3G -Dosgi.noShutdown=true -Dlogback.configurationFile=conf/logback.xml

press "Run". Protege should now start.

The above tested for Protege-5.0.0-beta-20-SNAPSHOT on Mac OS X 10.11.2, Eclipse 4.5.1 with PDE v. 3.11.1.v20150904-0345.

## Setup for just Protege plugin development

If one does not need to fiddle with Protege sources, e.g., just for development of Protege plugins (and not of Protege), one can use a simplified version of the setup:

Specifically skip the Steps 3, 5, and 6 above and at Step 4 additionally include the pre-compiled bundles `org.protege.*` (thus, excluding only `org.eclipse.equinox.*`)

I appreciate if this setup is tested, especially on Windows and Linux! Comments are welcomed!

### CODE REVIEW

**Comment by ykazakov** [comment]
I have now rebased this over the new master.
It would be nice if somebody of the P5 developers could take a look.

**Comment by matthewhorridge** [comment]
I'm not sure what these changes are for....

> 3. dependencies: removed unused dependencies in protege-common; 
in protege-desktop removed (unused?) jul.to.slf4j and log4j.over.slf4,
added log4j (required by org.protege.xmlcatalog)

The dependencies listed are used to capture Java logging and log4j stuff and redirect the output to slf4j.

**Comment by ykazakov** [comment]
sorry about this part comment, it is little outdated (I realised what was going on with log4j and reverted partially back):
log4j, judging by maven dependencies (maven dependency:tree) was used only by edu.sanford.protege:org.protege.xmlcatalog

so I just moved log4j.over.slf4 from protege.common to protege-editor-owl
If I do not do that then there are not very useful log4j import declarations generated in the Manifest of protege-editor-owl

regarding jul.to.slf4 I just did not find anything that uses it. Is it required by any plugin that suppose to be installed by Protege?

**Comment by matthewhorridge** [comment]
> log4j, judging by maven dependencies (maven dependency:tree) was used only by edu.sanford.protege:org.protege.xmlcatalog.  so I just moved log4j.over.slf4 from protege.common to protege-editor-owl

o.k. I see.  I would prefer to leave this in common for backwards compatibility.  If that's o.k. with you.

> regarding jul.to.slf4 I just did not find anything that uses it. Is it required by any plugin that suppose to be installed by Protege?

If third party plugins use Java logging this ensures that their log statements will get captured and logged nicely (and be visible in the new log view on the Views menu).  It gets placed into the bundles directory during the build.

**Comment by ykazakov** [comment]
OK, I can revert all logging dependencies to how they were initially.
But I *think* all those X.over.slf4 packages should be declared in protege-desktop rather than protege-common because protege-desktop defines which bundles should be available to other plugins in file-sets.xml.

**Comment by ykazakov** [comment]
B.t.w., thanks for mentioning the log view! In ELK we created our own. So probably we will switch to the Protege one if it is as nice as ours. :-)

**Comment by ykazakov** [comment]
OK, I reverted the dependencies in protege-common to how they were, but one should at least check / remove the versions of some plugins since (i) some versions are already declared in the parent pom and (ii) some of them are different: e.g., slf4j-api is v. 1.7.10 overrides v. 1.7.12 from parent pom (in eclipse I see several of warnings).

**Pull request merged**
