### PR TITLE
Basic Java 11 upgrade. 

### PR DESCRIPTION
**Pull request by ipetrova**
Tested for platform-independent distribution.

### CODE REVIEW

**Comment by ykazakov** [comment]
What is the difference to #846?

**Comment by ipetrova** [comment]
Hi Yevgeny,

I wasn’t aware there was a merge request for Java 11 upgrade. A took a quick look at the branch and the changes seem essentially the same (modulo some dependency version and the .gitignore). May I ask, is there some reason for having #846 still pending? We need a Protégé release supporting at least Java 11 for a plugin we are developing in our current project.
Thanks for your help.

**Comment by ykazakov** [comment]
I guess it is "pending" for several reasons:
1. All (popular) Protege plugins need to be updated to Java 11
1. Somebody need to test everything, particularly for Windows
1. Somebody needs to package JREs for platform-depended distributions
1. There was a change in Java licensing (by Oracle) which prevents bundling (Oracle) JREs 
1. The current Protege version still works just fine ;-)
1. The Protege maintainers (who can merge pull requests) do not have time

B.t.w., Java 11 is already outdated. The latest LTS version is Java 17.

**Comment by ipetrova** [comment]
I will take this by e-mail to explain you our situation.

**Comment by gouttegd** [comment]
Protégé 5.6.0, which uses/supports Java 11, is now out, so this PR is no longer relevant. Thanks for the contribution, @ipetrova, even though we did not use it.

**Pull request closed without merging**
