### PR TITLE
Process escape characters when searching for entities, fix #1217

### LINKED ISSUE #1217: Term completes then isn't accepted in class expression box
I have a term "Earth's Moon". When completing it completes as 'Earth\'s Moon', which it then red-underlines and won't accept.

### PR DESCRIPTION
**Pull request by ykazakov**
Previously this was done only when searching for OWLClasses

### CODE REVIEW

**Comment by ykazakov** [comment]
I added a few more commits to fix #910

**Comment by ykazakov** [comment]
Added a few more commits to improve escaping of strings and simplify the owl entity finder.

**Comment by ykazakov** [comment]
Added another fix related to #910

**Comment by gouttegd** [comment]
Merged, thanks!

**Pull request merged**
